### ISSUE TITLE
Please include `configure` and `Makefile.in`

### ISSUE THREAD

**Issue by gc00** [utwente-fmt/ltl2ba#1]
Thanks for this excellent tool.  however, your instructions seem to be out-of-date.  They say that it suffices to do `make`.

In order to configure and make, I ahd to do:
```
autoreconf --force --install --verbose
# This creates "configure" and "Makefile.in"
./configure
make
```

Could you please add the auto-generated `configure` and `Makefile.in` files to your git repo?
And after taht, could you please update the README to say to do:
`./configure && make`

And finally, although this may seem trivial, could you include in the `README`
a one-line example for users to test if it's working for them.  I'm thinking of
something like:

```
4. TESTING

For testing, try:
> ./ltl2ba -f '...'
```
(with a simple LTL formula), and then re-number `4. CHANGES` to `5. CHANGES`.

And as one final comment, could you convert the README file from ISO-8859
to the more modern UTF format for the umlaut of 'Büchi'?

Thanks again for this excellent software.

**Comment by trolando** [comment]
Hi @gc00 

Thanks for reaching out. I have made a few updates. First of all, you can now use CMake for compiling also, it's a bit faster than using autotools. I've updated the README, now encoded in UTF-8, and added a suggestion for testing. The instructions for compiling should now be clear.
